### ISSUE TITLE
[BUG] Same object gets used multiple times

### ISSUE THREAD

**Issue by HLWeil** [CSBiology/FSharpSpreadsheetML#2]
# Problem
When trying to iniate multiple spreadsheets in one process like this: 
```
let path1 = System.IO.Path.Combine (__SOURCE_DIRECTORY__,"file1.xlsx")
let path2 = System.IO.Path.Combine (__SOURCE_DIRECTORY__,"file2.xlsx")

let doc1 = Spreadsheet.initWithSST "sheet1" path1
let doc2 = Spreadsheet.initWithSST "sheet2" path2
```

The following error is thrown:

> System.ArgumentException: Cannot set the given root element to this part. The given part root element has already been associated with another OpenXmlPart.
Parameter name: partRootElement
   at DocumentFormat.OpenXml.Packaging.OpenXmlPart.SetDomTree(OpenXmlPartRootElement partRootElement)
   at FSharpSpreadsheetML.Spreadsheet.initWithSST(String sheetName, String path)
   at <StartupCode$FSI_0003>.$FSI_0003.main@() in C:\Users\HLWei\Downloads\FindFSharpSpreadsheetML_Error.fsx:line 23
Stopped due to error

**Comment by HLWeil** [comment]
The error was this line in Worksheet.fs: 

`let empty = Worksheet()`

Instead of creating a new worksheet everytime a new spreadsheet was created, the same worksheet was added to each spreadsheet, causing the program to fail.

Fixed in cbeeab2
